### ISSUE TITLE
ICC Cricket Application ( signInPage ) <4>

### ISSUE THREAD

**Issue by lahulnahian** [jueluddinsf/playwrightAutomation#53]
Test Scenario 4:

Go to @icc homepage
Verify sign in button
Create a account
then login in
verify the login

**Comment by lahulnahian** [comment]
Checking the code. I'll keep posted. Thanks.

**Comment by icc** [comment]
Go to @lahulnahian homepage
Verify does not know how GitHub works. 
Keep tagging random accounts.
